### ISSUE TITLE
Change minimal python version in `README.md`

### ISSUE THREAD

**Issue by tlentali** [tlentali/pycht#17]
Currently we maintain this project to be compatible with python 3.6 and above.  
However, python 3.6 is no longer supported or maintained by python's developers since beginning of 2022.
See [lts python version](https://devguide.python.org/versions/).

We need to upgrade the python version from 3.6 to 3.7 in the `README.md` :

https://github.com/tlentali/pycht/blob/31e3e5323f52eb556648e83d04be304bbf1cec37/README.md?plain=1#L56

**Comment by suzieboutard** [comment]
I can take this one!
